#!/bin/sh

set -e

case "$1" in
	start)
		echo "Loading aesd-char modules"
		module_load aesdchar
		;;
	stop)
		echo "Unloading aesd-char modules"
		module_unload aesdchar
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
